### ISSUE TITLE
variable $associations is empty in add::view but not in edit:view

### ISSUE THREAD

**Issue by DinoSane** [FriendsOfCake/crud-view#102] opened 2016-01-07 12:20 UTC
in a view, after an editAction the variable "$associations" is filled.

But if in a view, after an AddAction the variable "$associations" is empty.

**Comment by jippi** [comment] 2016-01-07 12:50
can't reproduce - please provide software versions and short test or gist with a reproducible way to verify

**Comment by DinoSane** [comment] 2016-01-07 16:43
cakephp3 and
 friendsofcake/bootstrap-ui (v0.3.3)
 friendsofcake/crud (4.2.4)
 friendsofcake/crud-view (dev-master 6d8f110)
 friendsofcake/crud-view (dev-master 6d8f110)
 friendsofcake/cakepdf (3.1.0)
 friendsofcake/search (1.2.0)

predioTable
        $this->hasMany('Pavimento', [
            'foreignKey' => 'Predio_id',
            'joinType' => 'INNER'
        ]);
PavimentoTable
        $this->belongsTo('Predio', [
            'foreignKey' => 'Predio_id',
            'joinType' => 'INNER'
        ]);
 Inflector::rules('uninflected', ['Predio']);
 Inflector::rules('uninflected', ['Pavimento']);

I have a incremental search "template/Pavimento/edit.ctp" shows $associations filled but
"template/Pavimento/add.ctp" shows $associations empty

I tried to buid a simplification of my project but i could not...

**Comment by DinoSane** [comment] 2016-01-07 17:54
Well, i dont know if it is a feature or not, but the $associations is not filled because the it is created within ViewListener.php:beforeFind.
So, since once on add actions a "find" is not fired before view, $associations is empty...

**Comment by josegonzalez** [comment] 2017-06-24 11:52
Closed by #110 :)

**Closed by josegonzalez** 2017-06-24 11:52 UTC
